<h1>Male Names</h1>

In [1]:
import pandas as pd

In [71]:
def male_names():
    
    data = pd.read_csv("Indian-Male-Names.csv")
    data['first_name'] = male_names['name'].str.split().str[0]
    newdata = male_names.drop(columns=["gender" , "name" , "race"])
    newdata.to_csv("male_first_names.csv" , index=False)

<h1>female names</h1>

In [72]:
def female_names():
    
    data = pd.read_csv("Indian-Female-Names.csv")
    data["first_name"] = data["name"].str.split().str[0]
    new_data = data.drop(columns=["name" , "gender" , "race"])
    new_data.to_csv("Female_fist_names.csv" , index= False)

<h1>Cast data</h1>

In [73]:
data = pd.read_csv("indian_caste_data.csv")

data.head()

       caste
0       abbi
1  abhyankar
2    abraham
3    acharya
4   achrekar

In [75]:
# call funtions
# male_names()
# female_names()

<h1>cities dataset clean</h1>

In [76]:
data = pd.read_csv("cities_r2.csv")
data.head()

,name_of_city,state_code,state_name,dist_code,population_total,population_male,population_female,0-6_population_total,0-6_population_male,0-6_population_female,...,literates_female,sex_ratio,child_sex_ratio,effective_literacy_rate_total,effective_literacy_rate_male,effective_literacy_rate_female,location,total_graduates,male_graduates,female_graduates
0,Abohar,3,PUNJAB,9,145238,76840,68398,15870,8587,7283,...,44972,890,848,79.86,85.49,73.59,"30.1452928,74.1993043",16287,8612,7675
1,Achalpur,27,MAHARASHTRA,7,112293,58256,54037,11810,6186,5624,...,43086,928,909,91.99,94.77,89.00,"21.257584,77.5086754",8863,5269,3594
2,Adilabad,28,ANDHRA PRADESH,1,117388,59232,58156,13103,6731,6372,...,37660,982,947,80.51,88.18,72.73,"19.0809075,79.560344",10565,6797,3768
3,Adityapur,20,JHARKHAND,24,173988,91495,82493,23042,12063,10979,...,54515,902,910,83.46,89.98,76.23,"22.7834741,86.1576889",19225,12189,7036
4,Adoni,28,ANDHRA PRADESH,21,166537,82743,83794,18406,9355,9051,...,45089,1013,968,68.38,76.58,60.33,"15.6322227,77.2728368",11902,7871,4031

In [77]:
cities = data["name_of_city"]

In [79]:
cities.head()

0       Abohar
1     Achalpur
2     Adilabad
3    Adityapur
4        Adoni
Name: name_of_city, dtype: object

In [81]:
cities.to_csv("cities.csv", index =False)

<h1>occupations</h1>

In [5]:
df = pd.read_csv("occupations.txt")

df.info()
df.to_csv("occupations.csv" , index = False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 914 entries, 0 to 913
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Accountant  914 non-null    object
dtypes: object(1)
memory usage: 7.3+ KB

In [8]:

branches = [
        "MG Road Branch",
        "Station Road Branch",
        "Civil Lines Branch",
        "Nehru Nagar Branch",
        "Vijay Nagar Branch",
        "Shastri Nagar Branch",
        "Gandhi Nagar Branch",
        "Laxmi Nagar Branch",
        "Rajendra Nagar Branch",
        "Jawahar Nagar Branch",
        "Ashok Nagar Branch",
        "Indira Nagar Branch",
        "Malviya Nagar Branch",
        "Shivaji Nagar Branch",
        "Adarsh Nagar Branch",
        "Model Town Branch",
        "Sadar Bazar Branch",
        "Cantt Branch",
        "Airport Road Branch",
        "Ring Road Branch",
        "University Road Branch",
        "Collectorate Branch",
        "High Court Branch",
        "Bus Stand Branch",
        "Railway Station Branch",
        "Market Yard Branch",
        "IT Park Branch",
        "MIDC Branch",
        "Sector 15 Branch",
        "Sector 22 Branch",
        "Sector 62 Branch",
        "Boring Road Branch",
        "Salt Lake Branch",
        "Park Street Branch",
        "Banjara Hills Branch",
        "Jubilee Hills Branch",
        "Anna Nagar Branch",
        "T. Nagar Branch",
        "Koramangala Branch",
        "Whitefield Branch",
        "Electronic City Branch",
        "Connaught Place Branch",
        "Karol Bagh Branch",
        "Dwarka Branch",
        "Noida Sector 18 Branch",
        "Gomti Nagar Branch",
        "Hazratganj Branch",
        "Alkapuri Branch",
        "Navrangpura Branch",
        "Satellite Branch"
]
df = pd.DataFrame(branches)
df.to_csv("branches_name.csv")

In [10]:
data = pd.read_csv("branches_name.csv")

In [11]:
data.head()

   Unnamed: 0                    0
0           0       MG Road Branch
1           1  Station Road Branch
2           2   Civil Lines Branch
3           3   Nehru Nagar Branch
4           4   Vijay Nagar Branch