In [ ]:
<h1>Male Names</h1>

In [89]:
import pandas as pd

In [90]:
def male_names():
    
    data = pd.read_csv("Indian-Male-Names.csv")
    data['first_name'] = male_names['name'].str.split().str[0]
    newdata = male_names.drop(columns=["gender" , "name" , "race"])
    newdata.to_csv("male_first_names.csv" , index=False)

<h1>female names</h1>

In [91]:
def female_names():
    
    data = pd.read_csv("Indian-Female-Names.csv")
    data["first_name"] = data["name"].str.split().str[0]
    new_data = data.drop(columns=["name" , "gender" , "race"])
    new_data.to_csv("Female_fist_names.csv" , index= False)

<h1>Cast data</h1>

In [92]:
data = pd.read_csv("indian_caste_data.csv")

data.head()

       caste
0       abbi
1  abhyankar
2    abraham
3    acharya
4   achrekar

In [93]:
# call funtions
# male_names()
# female_names()

<h1>cities dataset clean</h1>

In [94]:
cities = data["name_of_city"]

KeyError: 'name_of_city'

In [ ]:
cities.head()

In [ ]:
cities.to_csv("cities.csv", index =False)

<h1>occupations</h1>

In [ ]:
df = pd.read_csv("occupations.txt")

df.info()
df.to_csv("occupations.csv" , index = False)

In [ ]:
data = pd.read_csv("branches_name.csv")

In [ ]:
data.head()

In [ ]:
import pandas as pd
df = pd.read_csv("customers.csv")

In [ ]:
df.columns.tolist()

<h1>data correction for ML Algorithms</h1>

In [2]:
from sqlalchemy import create_engine,text
from sqlalchemy.engine import URL

from dotenv import load_dotenv
import os

load_dotenv()


url = URL.create(
        drivername="mysql+pymysql",
        username=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
        host=os.getenv("DB_HOST"),
        port=3306,
        database="Banking_analytics"
    )
engine = create_engine(url)

In [97]:
import pandas as pd
customers = pd.read_sql("customers", engine)
loans = pd.read_sql("loans" , engine)
accounts = pd.read_sql("accounts",engine)
transactions = pd.read_sql("transactions",engine)

print("CUSTOMERS")
print(customers.columns.tolist())

print("\nACCOUNTS")
print(accounts.columns.tolist())

print("\nLOANS")
print(loans.columns.tolist())

print("\nTRANSACTIONS")
print(transactions.columns.tolist())

CUSTOMERS
['customer_id', 'full_name', 'gender', 'dob', 'age', 'city', 'state', 'mobile', 'email', 'pan_number', 'aadhaar_number', 'marital_status', 'occupation', 'annual_income', 'cibil_score', 'account_type', 'account_number', 'ifsc_code', 'branch_name', 'account_opening_date', 'account_balance', 'loan_status']

ACCOUNTS
['account_id', 'customer_id', 'account_number', 'account_type', 'ifsc_code', 'branch_name', 'account_opening_date', 'account_balance']

LOANS
['loan_id', 'customer_id', 'loan_type', 'loan_amount', 'interest_rate', 'tenure_months', 'emi', 'loan_status', 'loan_start_date']

TRANSACTIONS
['transaction_id', 'account_id', 'transaction_date', 'transaction_type', 'transaction_mode', 'amount', 'balance_after_transaction', 'description']

In [98]:
print("Cutomers:" , customers.duplicated().sum())
print("acc:" , accounts.duplicated().sum())
print("loans:" , loans.duplicated().sum())
print("trac:" , transactions.duplicated().sum())

Cutomers: 0
acc: 0
loans: 0
trac: 0

In [99]:
print("Customers")
print(customers.isnull().sum())

print("\nAccounts")
print(accounts.isnull().sum())

print("\nLoans")
print(loans.isnull().sum())

print("\nTransactions")
print(transactions.isnull().sum())

Customers
customer_id             0
full_name               0
gender                  0
dob                     0
age                     0
city                    0
state                   0
mobile                  0
email                   0
pan_number              0
aadhaar_number          0
marital_status          0
occupation              0
annual_income           0
cibil_score             0
account_type            0
account_number          0
ifsc_code               0
branch_name             0
account_opening_date    0
account_balance         0
loan_status             0
dtype: int64

Accounts
account_id              0
customer_id             0
account_number          0
account_type            0
ifsc_code               0
branch_name             0
account_opening_date    0
account_balance         0
dtype: int64

Loans
loan_id            0
customer_id        0
loan_type          0
loan_amount        0
interest_rate      0
tenure_months      0
emi                0
loan_status        0
loan_start_date    0
dtype: int64

Transactions
transaction_id               0
account_id                   0
transaction_date             0
transaction_type             0
transaction_mode             0
amount                       0
balance_after_transaction    0
description                  0
dtype: int64

In [100]:
print("CUSTOMERS")
customers.info()

print("\nACCOUNTS")
accounts.info()

print("\nLOANS")
loans.info()

print("\nTRANSACTIONS")
transactions.info()

CUSTOMERS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   customer_id           100000 non-null  int64
 1   full_name             100000 non-null  object
 2   gender                100000 non-null  object
 3   dob                   100000 non-null  datetime64[ns]
 4   age                   100000 non-null  int64
 5   city                  100000 non-null  object
 6   state                 100000 non-null  object
 7   mobile                100000 non-null  object
 8   email                 100000 non-null  object
 9   pan_number            100000 non-null  object
 10  aadhaar_number        100000 non-null  object
 11  marital_status        100000 non-null  object
 12  occupation            100000 non-null  object
 13  annual_income         100000 non-null  int64
 14  cibil_score           100000 non-null  int64
 15  account_type          100000 non-null  object
 16  account_number        100000 non-null  int64
 17  ifsc_code             100000 non-null  object
 18  branch_name           100000 non-null  object
 19  account_opening_date  100000 non-null  datetime64[ns]
 20  account_balance       100000 non-null  int64
 21  loan_status           100000 non-null  object
dtypes: datetime64[ns](2), int64(6), object(14)
memory usage: 16.8+ MB

ACCOUNTS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   account_id            100000 non-null  int64
 1   customer_id           100000 non-null  int64
 2   account_number        100000 non-null  int64
 3   account_type          100000 non-null  object
 4   ifsc_code             100000 non-null  object
 5   branch_name           100000 non-null  object
 6   account_opening_date  100000 non-null  datetime64[ns]
 7   account_balance       100000 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(3), object(3)
memory usage: 6.1+ MB

LOANS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   loan_id          100000 non-null  int64
 1   customer_id      100000 non-null  int64
 2   loan_type        100000 non-null  object
 3   loan_amount      100000 non-null  float64
 4   interest_rate    100000 non-null  float64
 5   tenure_months    100000 non-null  int64
 6   emi              100000 non-null  float64
 7   loan_status      100000 non-null  object
 8   loan_start_date  100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(3), object(2)
memory usage: 6.9+ MB

TRANSACTIONS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 749024 entries, 0 to 749023
Data columns (total 8 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   transaction_id             749024 non-null  int64
 1   account_id                 749024 non-null  int64
 2   transaction_date           749024 non-null  datetime64[ns]
 3   transaction_type           749024 non-null  object
 4   transaction_mode           749024 non-null  object
 5   amount                     749024 non-null  float64
 6   balance_after_transaction  749024 non-null  float64
 7   description                749024 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(2), object(3)
memory usage: 45.7+ MB

In [101]:
customers[["age", "annual_income", "cibil_score", "account_balance"]].describe()

                 age  annual_income    cibil_score  account_balance
count  100000.000000   1.000000e+05  100000.000000     1.000000e+05
mean       48.521740   8.904536e+05     691.045320     1.824103e+06
std        18.183163   1.404768e+06     123.777418     6.590118e+06
min        17.000000   1.000000e+05     300.000000     1.000000e+03
25%        33.000000   2.670000e+05     625.000000     3.600000e+04
50%        49.000000   4.725000e+05     707.000000     1.250000e+05
75%        64.000000   8.950000e+05     783.000000     5.900000e+05
max        80.000000   1.000000e+07     900.000000     5.000000e+07

In [102]:
loans[[
    "loan_amount",
    "interest_rate",
    "tenure_months",
    "emi"
]].describe()

        loan_amount  interest_rate  tenure_months            emi
count  1.000000e+05  100000.000000  100000.000000  100000.000000
mean   2.224659e+06      12.198597      97.245000   40531.004231
std    2.451508e+06       2.965939      95.138702   31851.309848
min    5.000400e+04       8.000000      12.000000    1031.460000
25%    5.919442e+05       9.480000      36.000000   16687.497500
50%    1.139354e+06      11.770000      60.000000   30747.090000
75%    2.864090e+06      14.670000     120.000000   56864.437500
max    9.999808e+06      18.000000     360.000000  179399.400000

In [103]:
loans[[
    "loan_amount",
    "interest_rate",
    "tenure_months",
    "emi"
]].head(10)

   loan_amount  interest_rate  tenure_months       emi
0     844353.0          14.94             12  76185.97
1     591923.0           9.46             36  18949.97
2    5268589.0          15.56            360  68983.60
3    9700247.0           8.82            180  97350.39
4     488229.0           9.70             48  12312.53
5    4699251.0           9.59            120  61038.96
6    1971972.0          17.06            360  28209.99
7     275770.0          11.62             48   7210.74
8    4347976.0          13.42             84  80094.40
9      70483.0          11.35             60   1544.80

In [104]:
import numpy as np

r = loans["interest_rate"] / 100 / 12
n = loans["tenure_months"]
P = loans["loan_amount"]

calculated_emi = (
    P * r * (1 + r) ** n
) / (
    (1 + r) ** n - 1
)

emi_difference = abs(loans["emi"] - calculated_emi)

emi_difference.describe()

count    1.000000e+05
mean     2.495667e-03
std      1.442906e-03
min      6.188202e-09
25%      1.251820e-03
50%      2.500287e-03
75%      3.742720e-03
max      4.999965e-03
dtype: float64

In [105]:
transactions[[
    "amount",
    "balance_after_transaction"
]].describe()

              amount  balance_after_transaction
count  749024.000000               7.490240e+05
mean    27942.745494               1.831214e+06
std     24600.903997               6.576773e+06
min         0.000000               3.170000e+02
25%      7955.000000               5.624575e+04
50%     21498.000000               1.393270e+05
75%     40834.000000               5.751015e+05
max    100000.000000               5.007147e+07

In [106]:

(transactions["amount"] == 0).sum()

np.int64(510)

In [107]:
transactions = transactions[transactions["amount"] > 0].copy()

In [108]:
(transactions["amount"] <= 0).sum()

np.int64(0)

In [109]:
transactions["transaction_type"].value_counts()

transaction_type
Debit     523860
Credit    224654
Name: count, dtype: int64

In [110]:
transactions["transaction_mode"].value_counts()

transaction_mode
UPI             220597
Debit Card      157336
NEFT            138861
IMPS             82280
Credit Card      78256
Cash Deposit     44861
ATM              26323
Name: count, dtype: int64

In [111]:
transactions["description"].value_counts()

description
Fund Transfer       112392
Shopping            105123
Online Purchase     104510
Fuel                 52413
Restaurant           52174
Salary               44945
Cash Deposit         44861
EMI Payment          42125
Mobile Recharge      41777
Rent                 41729
ATM Withdrawal       26323
Electricity Bill     26169
Interest Credit      22456
Water Bill           15810
Insurance            15707
Name: count, dtype: int64

In [112]:
transactions["account_id"].nunique(), len(transactions)

(100000, 748514)

In [113]:
transactions = transactions.sort_values(
    ["account_id", "transaction_date"]
).copy()
transactions["previous_balance"] = (
    transactions.groupby("account_id")["balance_after_transaction"]
    .shift(1)
)

In [114]:
transactions["expected_balance"] = np.where(
    transactions["transaction_type"] == "Credit",
    transactions["previous_balance"] + transactions["amount"],
    transactions["previous_balance"] - transactions["amount"]
)

In [115]:
transactions["balance_difference"] = abs(
    transactions["balance_after_transaction"]
    - transactions["expected_balance"]
)

In [116]:
transactions["balance_difference"].describe()

count    648514.0
mean          0.0
std           0.0
min           0.0
25%           0.0
50%           0.0
75%           0.0
max           0.0
Name: balance_difference, dtype: float64

In [117]:
check = transactions.merge(
    accounts[["account_id", "account_opening_date"]],
    on="account_id",
    how="left"
)

invalid_transactions = (
    check["transaction_date"] < check["account_opening_date"]
)

invalid_transactions.sum()

np.int64(163112)

In [118]:
check.loc[
    invalid_transactions,
    [
        "account_id",
        "transaction_date",
        "account_opening_date"
    ]
].head(10)

    account_id transaction_date account_opening_date
0            1       2021-07-04           2023-01-11
1            1       2022-01-04           2023-01-11
2            1       2022-11-16           2023-01-11
3            1       2022-12-25           2023-01-11
22           4       2021-02-16           2021-06-17
38           6       2020-02-23           2025-12-28
39           6       2020-04-02           2025-12-28
40           6       2022-05-28           2025-12-28
41           6       2022-07-13           2025-12-28
42           6       2023-03-21           2025-12-28

In [119]:
check["date_difference"] = (
    check["transaction_date"] - check["account_opening_date"]
).dt.days

check["date_difference"].describe()

count    748514.000000
mean       4377.305472
std        5079.684427
min       -2381.000000
25%         257.000000
50%        2957.000000
75%        7427.000000
max       22443.000000
Name: date_difference, dtype: float64

In [120]:
(check["date_difference"] < 0).sum()

np.int64(163112)

In [121]:
transactions = transactions.merge(
    accounts[["account_id", "account_opening_date"]],
    on="account_id",
    how="left"
)

In [122]:
mask = transactions["transaction_date"] < transactions["account_opening_date"]

transactions.loc[mask, "transaction_date"] = (
    transactions.loc[mask, "account_opening_date"]
)

In [123]:
(
    transactions["transaction_date"]
    < transactions["account_opening_date"]
).sum()

np.int64(0)

In [124]:
transactions = transactions.sort_values(
    ["account_id", "transaction_date"]
).copy()

In [125]:
transactions["previous_balance"] = (
    transactions.groupby("account_id")["balance_after_transaction"]
    .shift(1)
)

In [126]:
transactions["expected_balance"] = np.where(
    transactions["transaction_type"] == "Credit",
    transactions["previous_balance"] + transactions["amount"],
    transactions["previous_balance"] - transactions["amount"]
)

In [127]:
transactions["balance_difference"] = abs(
    transactions["balance_after_transaction"]
    - transactions["expected_balance"]
)

In [128]:
transactions["balance_difference"].describe()

count    648514.0
mean          0.0
std           0.0
min           0.0
25%           0.0
50%           0.0
75%           0.0
max           0.0
Name: balance_difference, dtype: float64

In [129]:
transactions.columns.tolist()

['transaction_id',
 'account_id',
 'transaction_date',
 'transaction_type',
 'transaction_mode',
 'amount',
 'balance_after_transaction',
 'description',
 'previous_balance',
 'expected_balance',
 'balance_difference',
 'account_opening_date']

In [130]:
transactions = transactions.drop(
    columns=[
        "previous_balance",
        "expected_balance",
        "balance_difference",
        "account_opening_date"
    ]
)

In [131]:
transactions.columns.tolist()

['transaction_id',
 'account_id',
 'transaction_date',
 'transaction_type',
 'transaction_mode',
 'amount',
 'balance_after_transaction',
 'description']

In [132]:
print("Transaction IDs:", transactions["transaction_id"].nunique())
print("Total rows:", len(transactions))

Transaction IDs: 748514
Total rows: 748514

In [133]:
invalid_accounts = ~transactions["account_id"].isin(
    accounts["account_id"]
)
invalid_accounts.sum()

np.int64(0)

In [134]:
transactions["account_id"].value_counts().describe()

count    100000.000000
mean          7.485140
std           1.710634
min           2.000000
25%           6.000000
50%           7.000000
75%           9.000000
max          10.000000
Name: count, dtype: float64

In [135]:
accounts["customer_id"].nunique(), len(accounts)

(100000, 100000)

In [136]:
accounts["customer_id"].duplicated().sum()

np.int64(0)

In [137]:
invalid_loan_customers = ~loans["customer_id"].isin(
    customers["customer_id"]
)

invalid_loan_customers.sum()

np.int64(0)

In [138]:
invalid_transaction_accounts = ~transactions["account_id"].isin(
    accounts["account_id"]
)

invalid_transaction_accounts.sum()

np.int64(0)

In [139]:
customers["gender"].value_counts()

gender
Male      60182
Female    39818
Name: count, dtype: int64

In [140]:
customers["marital_status"].value_counts()

marital_status
Married    67255
Single     32745
Name: count, dtype: int64

<h1>Replace tables in SQl with new Cleaned DataFrames</h1>

In [142]:
transactions.to_sql(
    "transactions",
    engine,
    if_exists="replace",
    index=False
)

748514

In [145]:
pd.read_sql(
    "select count(*) as total from transactions",
    engine
)

    total
0  748514